{"name": "test_InvalidLogin", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testCases.test_invalidLogin.Test_Case_003_InvalidLogin object at 0x105ecc070>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d1f41b41daed8f821e9451a383d53501\")>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_InvalidLogin(self, setup):\n        self.logger.info(\"********* Test Case 000 Invalid User ******\")\n        self.driver = setup\n        self.driver.get(self.baseUrl)\n        self.driver.maximize_window()\n        self.invalid_login = InvalidLoginPage(self.driver)\n        self.invalid_login.clickSigninHyperLink()\n        time.sleep(2)\n        assert \"Login to your account\" in self.invalid_login.getLoginIntoAccountText()\n        self.invalid_login.enterInvalidLoginEmail(self.email_address)\n        self.invalid_login.enterInvalidLoginPassword(self.password)\n        self.invalid_login.clickLoginButton()\n        time.sleep(2)\n        if self.invalid_login.getErrorMessageText() == \"Your email or password is inco\":\n            assert True\n            self.logger.info(\"********* Test Pass ******\")\n        else:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"invalid_login\", attachment_type=AttachmentType.PNG)\n            self.driver.save_screenshot(\"./Screenshots/\" + \"test_InvalidLogin.png\")\n            self.logger.info(\"********* Test Fail ******\")\n>           assert False\nE           assert False\n\ntestCases/test_invalidLogin.py:40: AssertionError"}, "attachments": [{"name": "invalid_login", "source": "cc1c77d2-3ce3-434e-9745-7dbf0971c234-attachment.png", "type": "image/png"}, {"name": "log", "source": "71e67866-881b-4772-ac57-b2f22fcf59df-attachment.txt", "type": "text/plain"}], "start": 1690638098989, "stop": 1690638120989, "uuid": "2677053f-44df-42a3-8881-742ac6fccd52", "historyId": "6e3a478ccb2726e315d39b41a5f804fd", "testCaseId": "6e3a478ccb2726e315d39b41a5f804fd", "fullName": "testCases.test_invalidLogin.Test_Case_003_InvalidLogin#test_InvalidLogin", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_invalidLogin"}, {"name": "subSuite", "value": "Test_Case_003_InvalidLogin"}, {"name": "host", "value": "Salmans-Mac.local"}, {"name": "thread", "value": "24932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_invalidLogin"}]}